config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  devise_for :users, :path => '', path_names: { sign_in: "login", sign_out: "logout", sign_up: "registration"}
  root 'static_pages#home'
  resources :users
  resources :posts do
  	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	has_rich_text :content
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 5000}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable, :lockable
  has_many :posts, dependent: :destroy
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 250}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  validates :password, presence: true, length: {maximum: 6}
  validates :password_confirmation, presence: true, length: {maximum: 6}

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
	  before_action :configure_permitted_parameters, if: :devise_controller?

	  def after_sign_in_path_for(resource)
	  	current_user
	  end

	  def after_sign_up_path_for(resource)
	  	current_user
	  end

  protected
  def configure_permitted_parameters
    attributes = [:name, :email, :password, :password_confirmation, :avatar]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comments_params)
		 if @comment.save
      redirect_to @post
    else
      redirect_to post_path(@post)
    end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to @post
	end

	private
	def comments_params
		params.require(:comment).permit(:name, :body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def create
		if current_user.nil?
			flash[:success] = "Please log in or signup first to write your own post on Blog app"
			redirect_to new_user_session_path
		else
		  @post = current_user.posts.build(posts_params)
		  if @post.save
			  flash.now[:success] = "Your blog has been created and posted to your profile page....."
			  redirect_to current_user
		  else
			  redirect_to current_user
			end
		end
	end

	def destroy
		@post = current_user.posts.find(params[:id])
		@post.delete
		flash[:success] = "Your Blog has been deleted successfully."
		redirect_to current_user
	end

	def new
		@post = Post.new(params[:post])
	end

	def show
		if current_user.nil?
			flash[:success] = "Please log in or signup first to see others post on Blog app"
			redirect_to new_user_session_path
	  else
		  @post = current_user.posts.find_by_id(params[:id])
		  @user = User.find(params[:id])
		  @posts = @user.posts
		  @comment = Comment.new
		  @comments = @post.comments
	  end
	end

	private
	def posts_params
		params.require(:post).permit(:content)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    redirect_to new_user_session_path
  end

  # def create
  # 	user = User.find_by(email: params[:session][:email].downcase)
  # 	if user && user.authenticate(params[:session][:password])
  # 		log_in user
  # 		redirect_to user
  # 		else
  # 			flash.now[:danger] = "Invalid email/password"
  # 			render 'new'
  # 	end
  # end

  # def destroy
  # 	log_out
  # 	redirect_to new_user_session_path
  # end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def new
  # 	@user = User.new
  # end

  def index
    @users = User.all
  end

  # def edit
  #   @user = User.find(params[:id])
  # end

  # def update    
  # end

  def show
  	@user = User.find(params[:id])
    #@posts = @user.posts
  end

  # def create
  # 	@user = User.new(user_params)
  # 	if @user.save
  # 		flash[:success] = "Welcome to Blog app, start blogging"
  # 		log_in @user
  # 		redirect_to @user
  # 	else
  # 		render 'new'
  # 	end
  # end

  # private
  # def user_params
  # 	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = 'blog'
		if (page_title.empty?)
			base_title
		else
			page_title + ' | ' + base_title
		end
	end

	def header(text)
		content_for(:header) {text.to_s}
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# def log_in(user)
	# 	session[:user_id] = user.id
	# end

	# def log_out
	# 	session.delete(:user_id)
	# 	@current_user = nil
	# end

	# def current_user
	# 	@current_user ||= User.find_by(id: session[:user_id])
	# end

 #  # return true if the user logged in
	# def logged_in?
	# 	!@current_user.nil?
	# end

	def current_user?(user)
		user == current_user
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<% @comments.each do |c| %>
  <p>
    <%= c.name %><a> :- </a>
    <%= c.body %>
    <%= link_to "Delete", post_comment_path(c.post_id, c.id), method: :delete %>
  </p>
<% end %>

app/views/comments/_comments.html.erb
<li id="comment-<%= comment.id %>">
  <span class ="comment"><%= commen.name%></span>
  <span class ="comment"><%= commen.commnet%></span>
  <span class ="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    <% if current_user?(commnet.user) %>
    <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
    <% end %>
  </span>
</li>

app/views/comments/_form.html.erb
<%= form_for ([@post, @comment]) do |f| %>
  <p>
  	<%= f.label :name %>
  	<%= f.text_field :name %></br>
  </p>

  <p>
  	<%= f.label :body %>
  	<%= f.text_area :body %></br>
  </p>

  <p>
  	<%= f.submit "Add a comment" %>
  </p>
<%end %>

app/views/comments/new.html.erb
<% provide(:title, "Comment") %>
<h1>Add comment</h1>
<%= form_for(@comment) do |f| %>
  <div class="field">
  	<%= f.label :name %>
    <%= f.text_field :name %>
  	<%= f.label :comment %>
    <%= f.text_area :comment, placeholder: "Add comment..." %>
  </div><%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> | Blog app </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blog", '#', id: "logo" %>
          <nav>
            <ul class="nav navbar-nav navbar-right">
               <% if !current_user.nil? %> 
                <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
              <% end %>
            </ul>
          </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert
        alert-#{message_type}") %>
      <% end %>
    </div>      
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    <% if current_user?(post.user) %>
      <%= link_to "delete", post, method: :delete, data: {confirm: "Are you sure?"} %>
      <%= link_to "comment", new_comment_path, class: "btn btn-lg btn-primary" %>
    <% end %>
  </span>
</li>

app/views/posts/new.html.erb
<% provide(:title, "Create_post") %>
<h1>Compose Post</h1>
<%= form_for(@post) do |f| %>
  <div class="field">
  	<%= f.label :style_content %>
    <%= f.rich_text_area :content, placeholder: "Compose new post..." %>
  </div><%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<h3></a> Posts (<%= @user.posts.count %>)</h3>
<ol class="posts">
  <%= render @posts %>
      <br>
    <div class="col-md-8">        
      <h2> Comments </h2>
      <%= render 'comments/comment' %>
      <h3>Add a Comment: </h3>
      <%= render 'comments/form'%>       
    </div>
    <br>
</ol>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
  <div class="center jumbotron">
    <% provide(:title, "Home") %>
    <h1>BLOG APP</h1>
    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Sign in!", new_user_session_path, class: "btn btn-lg btn-primary" %>
  </div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>Users of Blog app</h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>,
      <%= link_to user.email, user %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <li><%= @user.name %></li>
        <br>
        <li><%= @user.email %></li>
        <br>
      </h1>
      <%= link_to "Compose new Post", new_post_path , class: "btn btn-lg btn-primary" %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.posts.any? %>
  <%= link_to "Show Post", post_path , class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
</div>